### ISSUE TITLE
Little more documentation need

### ISSUE THREAD

**Issue by 99hops** [answear/messenger-heartbeat-bundle#3]
Hello @mglowala can you please explain why we need this bundle and this can't be handled by `heartbeat` configuration. I recently hit on a `"Library error: a socket error occurred"` error inside long lived job and I am looking for the possible solutions to this. Thanks a lot!

**Comment by mpoiriert** [comment]
I just installed the bundle for the same reason

You can read this 

https://blog.mollie.com/keeping-rabbitmq-connections-alive-in-php-b11cb657d5fb

**Comment by malarzm** [comment]
Symfony's `heartbeat` is using librabbitmq: 

https://github.com/symfony/symfony/blob/76b7a7e95691d02ada1d24a6b1d9dadcab047d8d/src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php#L153-L155

Our bundle uses PCNTL to handle heartbeat: https://github.com/answear/messenger-heartbeat-bundle/blob/master/src/Heartbeat/PCNTLHeartbeatSender.php

Hope this is enough explaination :)
